### ISSUE TITLE
How configure my app for MessageBuilder?

### ISSUE THREAD

**Issue by KingYes** [mcrumm/phlack#11]
I just get this error:
```
Result:
object(Crummy\Phlack\Bridge\Guzzle\Response\MessageResponse)#467 (1) {
  ["data":protected]=>
  array(3) {
    ["status"]=>
    int(404)
    ["reason"]=>
    string(9) "Not Found"
    ["text"]=>
    string(8) "No hooks"
  }
}
```

Which are service I need to use?

**Comment by mcrumm** [comment]
Slack made some changes to their Incoming Webhooks API.  When you create an Incoming Webhook, Slack will give you a URL like: https://hooks.slack.com/services/ZZZZZZZZZ/YYYYYYYYY/XXXXXXXXXXXXXXX

The last segment of the URL (XXXXXXXXXXXXXXX) is the token.

FYI, I will be deprecating this library soon, as I haven't had time to keep it up-to-date.  I would recommend either [maknz/slack](https://packagist.org/packages/maknz/slack) or [cleentfaar/slack](https://packagist.org/packages/cleentfaar/slack) as an alternative.

**Comment by KingYes** [comment]
Thanks
